const imperum = {
	user:{
		name: "example@example.com",
		password:"mysecretpassword"
	},
	about:{
		missionheader:"Wij zijn Imperum",
		missionpara:"Ervaren Webdevelopers en Online Marketeers",
		quote1: "We don't just make websites,",
		quote2: "we make websites that sell.",
		servicesitem1:"Google Bedrijfsprofiel",
		servicespara1: "Het is heel belangrijk dat uw bedrijf door Google erkend is. Dankzij dit kunnen uw toekomstige klanten u vinden in de grootste zoekmachine ter wereld." ,
		servicesitem2: "Zoekmachine Optimisatie",
		servicespara2: "Wij zorgen dat uw bedrijf online zichtbaar is.",
		servicesitem3: "Social Media",
		servicespara3: "Wij helpen u social media campagnes te starten."
	},
	offert:{
		introductionheader:"Wij bieden een compleet pakket van geïntegreerde services op maat van uw behoeften.",
		shortpara1:"Onze uniciteit en onderscheid ligt in het feit dat we elke klant individueel benaderen.",
		shortpara2:"Bent u een eenmansbedrijf die ambitie hebt om een lokale tycoon in uw branche te worden?",
		shortpara3:"We hebben voor idereen de juiste oplossing !",
		starterheader:"Starter",
		starterparatext1:"Wilt u dat uw website uw bedrijf elegant en professioneel presenteert? ",
		starterparatext2:"Dat uw bezoekers duidelijk en makkelijk kunnen ervan weten welke diensten biedt u aan en hoe best met u contact opnemen?",
		starterparatext3:"Maar u hebt geen extra funcionaliteit nodig, zoals online afspraak maken, eigen email adres of verkeersanalyse en strategie.",
		starterparatext41:"Dan is onze ",
		starterparatext42:" Pakket misschien iets voor u !",
		starterpriceleft:"voor slechts",
		starterpriceright:"per maand",	
		starterdescriptionheader:"Wat krijgt u?",
		starterprice:"12",
		starterdescriptiondnl:"Domain naam",
		starterdescriptiondnr:"U kunt kiezen uit .nl .com .org en meer. Als domeinnaam is niet bezet valt het onder standaard abonnament kosten.",
		starterdescriptionhl:"Hosting",
		starterdescriptionhr:'Uw website heeft een server nodig om op te "leven". Onze kwaliteit servers zijn snel en betrauwbaar.',
		starterdescriptioncdl:"Custom Design",
		starterdescriptioncdr:"Wij maken uw website volgens uw bedrijfs design. Wij benaderen onze klanten individueel en maken unique websites volgens door u gekozen stijl.",
		starterdescriptionpwl:"tot 3 paginas Website",
		starterdescriptionpwr:"Naast uw main web pagina heeft u nog mogelijkheid om twee andere onderdelen. Tot 15 paragrafen per pagina. Misschien Contact, Prijzen of Services? Heeft u meer nodig? Kies onze PRO of ADVANCED pakket.",
		starterdescriptiongtwl:"Gratis text wijzigingen",
		starterdescriptiongtwr:'Voor dit pakket geld gratis inhoud wijzigingen tot 10 paragrafen per jaar. Wilt u unlimited wijzigingen? Kies onze PRO of ADVANCED pakket.',
		proheader:"Pro",
		proparatext1:"Bent u een eenmansbedrijf, freelancer of heeft u een kleine zaak?",
		proparatext2:"Wilt u dat uw website zich scherp en professioneel presenteert?",
		proparatext3:"Wilt u dat uw website uw bedrijf ook verkoop?",
		proparatext4:"Wij maken uw website online zichtbaar, zodat uw hudige en potentiële klanten kunnen uw bedrijf makkelijk vinden.",
		propriceleft:"voor slechts",
		propriceright:"per maand",	
		prodescriptionheader:"Wat krijgt u?",
		proprice:"19",
		prodescriptiondnl:"Domain naam",
		prodescriptiondnr:"U kunt kiezen uit .nl .com .org en meer. Als domeinnaam is niet bezet valt het onder standaard abonnament kosten.",
		prodescriptionhl:"Hosting & Database",
		prodescriptionhr:'Uw website heeft een server nodig om op te "leven". Onze kwaliteit servers zijn snel en betrauwbaar. Om uw bezoekers beter ervaring te bieden hebt uw website meer functionaliteit nodig. Bijvoorbeeld online afspraak maken! Of aanbieden de inhoud die aangepast aan de voorkeuren van bezoekers is. Daarvoor heeft uw website ook een database nodig.',
		prodescriptioncdl:"Custom Design",
		prodescriptioncdr:"Wij maken uw website volgens uw bedrijfs design. Wij benaderen onze klanten individueel en maken unique websites volgens door u gekozen stijl.",
		prodescriptionpwl:"tot 5 paginas Website",
		prodescriptionpwr:"Naast uw main web pagina heeft u nog mogelijkheid om vier andere onderdelen. Tot 20 paragrafen per pagina. Misschien Contact, Prijzen of Services? Heeft u meer nodig? Kies onze ADVANCED pakket.",
		prodescriptiongtwl:"Gratis text wijzigingen",
		prodescriptiongtwr:'Voor dit pakket geld gratis unlimited text inhoud wijzigingen. Dankzij ons geautomatiseerde updateproces kunt u de inhoud van uw site regelmatig bijwerken.',
		prodescriptioncfl:"Contact formulier",
		prodescriptioncfr:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		prodescriptionasl:"Analyse en Strategie",
		prodescriptionasr:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		prodescriptiongbpl:"Google bedrijsprofiel",
		prodescriptiongbpr:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		advancedheader:"Advanced",
		advancedparatext1:"Onze uniciteit en onderscheid ligt in het feit dat we elke klant individueel benaderen.",
		advancedparatext2:"Het maakt niet uit of u een eenmansbedrijf bent of dat u de ambitie hebt om een lokale tycoon in uw branche te worden.",
		advancedparatext3:"We hebben voor idereen de juiste oplossing",
		advancedparatext4:"We hebben voor idereen de juiste oplossing !",
		advancedpriceleft:"voor slechts",
		advancedpriceright:"per maand",	
		advanceddescriptionheader:"Wat krijgt u?",
		advancedprice:"29",
		advanceddescriptiondnl:"Domain naam",
		advanceddescriptiondnr:"U kunt kiezen uit .nl .com .org en meer. Als domeinnaam is niet bezet valt het onder standaard abonnament kosten.",
		advanceddescriptionhl:"Hosting & Database",
		advanceddescriptionhr:'Uw website heeft een server nodig om op te "leven". Onze kwaliteit servers zijn snel en betrauwbaar. Om uw bezoekers beter ervaring te bieden hebt uw website meer functionaliteit nodig. Bijvoorbeeld online afspraak maken! Of aanbieden de inhoud die aangepast aan de voorkeuren van bezoekers is. Daarvoor heeft uw website ook een database nodig.',
		advanceddescriptioncdl:"Custom Design",
		advanceddescriptioncdr:"Wij maken uw website volgens uw bedrijfs design. Wij benaderen onze klanten individueel en maken unique websites volgens door u gekozen stijl.",
		advanceddescriptionpwl:"tot 10 paginas Website",
		advanceddescriptionpwr:"Naast uw main web pagina heeft u nog mogelijkheid om negen andere onderdelen. Tot 30 paragrafen per pagina.",
		advanceddescriptiongtwl:"Gratis text wijzigingen",
		advanceddescriptiongtwr:'Voor dit pakket geld gratis unlimited text inhoud wijzigingen. Dankzij ons geautomatiseerde updateproces kunt u de inhoud van uw site regelmatig bijwerken.',
		advanceddescriptioneel:"Eigen email",
		advanceddescriptioneer:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		advanceddescriptioncfl:"Contact formulier",
		advanceddescriptioncfr:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		advanceddescriptionasl:"Analyse en Strategie",
		advanceddescriptionasr:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		advanceddescriptiongbpl:"Google bedrijsprofiel",
		advanceddescriptiongbpr:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		advanceddescriptionsl:"Support",
		advanceddescriptionsr:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
	},
	landing:{
		boardheader:"Wij creëren uw online merk",
		boardpara1:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		boardpara2:"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		servicesheader1:"Web Design",
		servicespara1:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		servicesbutton1:"Meer",
		servicesheader2:"Seo",
		servicespara2:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		servicesbutton2:"Meer",
		servicesheader3:"Online Marketing",
		servicespara3:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		servicesbutton3:"Meer",
		responsiveheader:"Responsive Design",
		responsivepara:"In de wereld bestaan meer dan 35 milijard apparaten die met Internet kunnen verbinden. Laptops, PC's, tablets, mobieltjes - bijna idereen maakt dagelijks gebruik van een van die apparaten. Daarom is het heel belangrijk dat jouw website goed eruitziet op verschillende schermresoluties.",
		packagesheader:"Website pakkets & prijzen",
		packagesstarterheader:"Starter",
		packagesstarterprice:"12",
		packagesstarterpricesub:"per maand",
		packagesstarterlist1:" 1 jaar contract",
		packagesstarterlist2:" Domein naam",
		packagesstarterlist3:" Hosting",
		packagesstarterlist4:" tot 3 Paginas",
		packagesstarterlist5:" Voorwaarden",
		packagesstarterlist6:" Persoonlijk advies",
		packagesstarterbutton:"Select",
		packagesproheader:"Pro",
		packagesproprice:"19",
		packagespropricesub:"per maand",
		packagesprolist1:" 1 jaar contract",
		packagesprolist2:" Domein naam",
		packagesprolist3:" Hosting & Database",
		packagesprolist4:" tot 5 Paginas",
		packagesprolist5:" Contact Form",
		packagesprolist6:" Persoonlijk advies",
		packagesprobutton:"Select",
		packagesadvancedheader:"Advanced",
		packagesadvancedprice:"29",
		packagesadvancedpricesub:"per maand",
		packagesadvancedlist1:" 1 jaar contract",
		packagesadvancedlist2:" Domein naam",
		packagesadvancedlist3:" Hosting & Database",
		packagesadvancedlist4:" tot 10 Paginas",
		packagesadvancedlist5:" Eigen email",
		packagesadvancedlist6:" Support",
		packagesadvancedbutton:"Select",
		reviewsheader:"Klantwaardering",
		reviewsquote1:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		reviewsquote2:"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		reviewsquote3:"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Tempor incididunt ut labore et dolore magna aliqua."
	}
}

module.exports = {
	imperum
}